apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: service-account-{{ .Values.authentication.client.clientId }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "kafka-broker-2.labels" . | nindent 4 }}
    strimzi.io/cluster: {{ include "kafka-broker-2.name" . }}
  annotations:
    {{- include "kafka-broker-2.argocd-syncwave" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  {{- if eq .Values.authorization "simple" }}
  authorization:
    type: simple
    acls:
      - operations:
          - Describe
          - DescribeConfigs
        resource:
          type: cluster
      - operations:
          - Create
          - Describe
          - Read
          - Write
          - Delete
        resource:
          name: '*'
          patternType: literal
          type: topic
      - operations:
          - Read
          - Describe
          - Delete
        resource:
          name: '*'
          patternType: literal
          type: group
      - operations:
          - Read
          - Describe
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
  {{- end }}
