{{- if .Values.kafka.controller.enabled -}}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {{ include "kafka-broker-2.name" . }}-controller
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    strimzi.io/cluster: {{ include "kafka-broker-2.name" . }}
  annotations:
    {{- include "kafka-broker-2.argocd-syncwave" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: {{ .Values.kafka.controller.replicas }}
  roles:
    - controller
  resources:
    {{- toYaml .Values.kafka.controller.resources | nindent 4 }}
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
{{ end }}