{{- if .Values.kafka.listener.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-broker-1.name" . }}-tls-secret
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "kafka-broker-1.labels" . | nindent 4 }}
  annotations:
    {{- include "kafka-broker-1.argocd-syncwave" . | nindent 4 }}
data:
  {{ .Values.kafka.listener.external.tls.secret.key.crt }}: >-
    {{ .Values.kafka.listener.external.tls.secret.value.crt }}
  {{ .Values.kafka.listener.external.tls.secret.key.key }}: >- 
    {{ .Values.kafka.listener.external.tls.secret.value.key }}
type: Opaque
{{- end }}