{{- if eq .Values.authentication.saslMechanism "SCRAM-SHA-512" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.authentication.clientId }}-user-secret
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "kafka-broker-1.labels" . | nindent 4 }}
  annotations:
    {{- include "kafka-broker-1.argocd-syncwave" . | nindent 4 }}
stringData:
  clientSecret: {{ .Values.authentication.clientSecret }}
type: Opaque
{{- end }}
