keycloak:
  name: keycloak

realm:
  name: amqstreams-console

hook:
  image:
    repository: quay.io/cloud-architecture-workshop/wait-for-statefulset-job
    pullPolicy: IfNotPresent
    tag: "1c68180"
  serviceAccount:
    create: true
    name: ""
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  maxTimeToWait: 120000

users:
  users:
    - id: dev1      
      groups:
        - developers
        - devteam1
    - id: dev2
      groups:
        - developers
        - devteam1
    - id: admin1
      groups:
        - admins
    - id: admin2
      groups:
        - administrators
  password:

groups:
  - name: developers
    roles: 
      - developers
  - name: devteam1
    roles:
      - developers
  - name: administrators
    roles:
      - administrators

roles:
  - name: developers
  - name: administrators

client:
  amqstreams:
    name:
    secret:

argocd:
  enabled: true
  syncwave: "-1"

