apiVersion: v2
name: amq-streams
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: amq-streams-operator
    version: 0.1.0
    repository: file://amq-streams-operator
  - name: amq-streams-console-operator
    version: 0.1.0
    repository: file://amq-streams-console-operator
  - name: kafka-broker-1
    version: 0.1.0
    repository: file://kafka-broker-1
    condition: kafka1.enabled
  - name: kafka-broker-2
    version: 0.1.0
    repository: file://kafka-broker-2
    condition: kafka2.enabled
  - name: amq-streams-console-anonymous
    version: 0.1.0
    repository: file://amq-streams-console-anonymous
    condition: console.anonymous.enabled
  - name: amq-streams-console-oauth
    version: 0.1.0
    repository: file://amq-streams-console-oauth
    condition: console.oauth.enabled
  - name: kafka-topics-1
    version: 0.1.0
    repository: file://kafka-topics-1
    condition: kafka2.enabled
  - name: kafka-topics-2
    version: 0.1.0
    repository: file://kafka-topics-2
    condition: kafka2.enabled
  - name: keycloak-realm-import-console-oauth
    version: 0.1.0
    repository: file://keycloak-realm-import-console-oauth
    condition: console.oauth.enabled
