{{- if .Values.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  annotations:
    {{- include "amq-streams-console-oauth-namespace.argocd-syncwave" . | nindent 4 }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
{{- end }}