apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datagen-consumer.name" . }}
  labels:
    {{- include "datagen-consumer.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-

    {{- range $key, $value := .Values.logLevel }}
    quarkus.log.category."{{ $key }}".level={{ $value }}
    {{ end }} 

    datagen.consumer-group-prefix={{ .Values.datagen.consumerGroupPrefix }}
    datagen.partitions-per-topic={{ .Values.datagen.partitionsPerTopic }}
    datagen.topics-per-consumer={{ .Values.datagen.topicsPerConsumer }}
    datagen.consumer-groups={{ .Values.datagen.consumerGroups }}
    datagen.topic-name-template={{ .Values.datagen.topicNameTemplate }}

    {{- range $key, $value := .Values.datagen.kafka }}
    datagen.kafka.{{ $key }}.name={{ $key }}
    {{- range $key2, $value2 := $value.configs}}
    datagen.kafka.{{ $key }}.configs.{{ $key2 }}={{ $value2}}
    {{- end }}  
    {{- end }}